
const fs = require('fs');
const path = require('path');

const KB_FILE = path.join(__dirname, 'knowledge_base.json');

const newLinks = [
    "https://www.youtube.com/watch?v=Nxg0vQk05os&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=2&t=2s",
    "https://www.youtube.com/watch?v=99IecSRWA5Y&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=3",
    "https://www.youtube.com/watch?v=_GzSfnJNNI4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=4",
    "https://www.youtube.com/watch?v=ElA_-dnAkak&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=5",
    "https://www.youtube.com/watch?v=fxToPMQ4_0A&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=6",
    "https://www.youtube.com/watch?v=MQUUAIzEAVg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=7",
    "https://www.youtube.com/watch?v=fxyt35_Bh-M&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=8",
    "https://www.youtube.com/watch?v=JJXNVS_-tGI&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=9",
    "https://www.youtube.com/watch?v=SMHoIkrbFyY&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=10",
    "https://www.youtube.com/watch?v=k2H3cJL1M9A&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=11",
    "https://www.youtube.com/watch?v=sWKk5ytBCTE&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=12",
    "https://www.youtube.com/watch?v=CKdSDn5m0dM&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=13",
    "https://www.youtube.com/watch?v=aCC3_58SlgI&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=14",
    "https://www.youtube.com/watch?v=PQsHE4BQYDw&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=15",
    "https://www.youtube.com/watch?v=ZIGBr2Mle1w&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=16",
    "https://www.youtube.com/watch?v=t4Fxrr_aCH4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=17",
    "https://www.youtube.com/watch?v=5ymU3Xojjq4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=19",
    "https://www.youtube.com/watch?v=ZsRx_FH_-No&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=20",
    "https://www.youtube.com/watch?v=2ORhTGsxn1M&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=21",
    "https://www.youtube.com/watch?v=ncD-4NIFMLI&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=22",
    "https://www.youtube.com/watch?v=u6CHfqS2scA&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=23",
    "https://www.youtube.com/watch?v=996ut5cDW_Y&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=24",
    "https://www.youtube.com/watch?v=uAiQLcNC8Og&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=25",
    "https://www.youtube.com/watch?v=Jxu1L7glK9c&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=26",
    "https://www.youtube.com/watch?v=bdNEPA0fInA&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=27",
    "https://www.youtube.com/watch?v=qqHm_s0e3E4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=28",
    "https://www.youtube.com/watch?v=n4R_OoaejQo&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=29",
    "https://www.youtube.com/watch?v=mUkDttf1awU&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=30",
    "https://www.youtube.com/watch?v=0fps14OqofU&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=31",
    "https://www.youtube.com/watch?v=wnMrUvzlF-Q&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=32",
    "https://www.youtube.com/watch?v=lA5GLNhYuB4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=33",
    "https://www.youtube.com/watch?v=7TAr8tmlGTg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=34",
    "https://www.youtube.com/watch?v=bLJeIRoTcRI&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=35",
    "https://www.youtube.com/watch?v=u5iEBRMR-lw&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=36",
    "https://www.youtube.com/watch?v=D5Rw3neWEGE&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=37",
    "https://www.youtube.com/watch?v=ZSdUBgs0TVE&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=38",
    "https://www.youtube.com/watch?v=Fwr0DpKr9Qc&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=39",
    "https://www.youtube.com/watch?v=8NYvry24ajo&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=40",
    "https://www.youtube.com/watch?v=4BbgJrdC75I&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=41",
    "https://www.youtube.com/watch?v=3B-rWczQrdY&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=42",
    "https://www.youtube.com/watch?v=LBp1-yHCBYo&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=43",
    "https://www.youtube.com/watch?v=3KYyk7r6Omg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=44",
    "https://www.youtube.com/watch?v=vX5AOF4Wdgo&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=45",
    "https://www.youtube.com/watch?v=ZwV8y_7jt_4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=46",
    "https://www.youtube.com/watch?v=bL97Ekp9eZk&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=47",
    "https://www.youtube.com/watch?v=TTAjJS6cr-s&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=48",
    "https://www.youtube.com/watch?v=xOjd5QKJTWg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=49",
    "https://www.youtube.com/watch?v=-pC3SyyXeTI&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=50",
    "https://www.youtube.com/watch?v=mT-tvWY2S08&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=51",
    "https://www.youtube.com/watch?v=venU_5fqThU&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=52",
    "https://www.youtube.com/watch?v=xai8g7tt_jU&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=53",
    "https://www.youtube.com/watch?v=7NlUT-oo2GE&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=54",
    "https://www.youtube.com/watch?v=OM0eXE_K6Mc&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=55",
    "https://www.youtube.com/watch?v=txmg__Jpawc&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=56",
    "https://www.youtube.com/watch?v=Ra368cApYM0&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=57",
    "https://www.youtube.com/watch?v=YjRzW9EUyHQ&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=58",
    "https://www.youtube.com/watch?v=ZkT5SyjewgY&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=59",
    "https://www.youtube.com/watch?v=6fnVX-2q6FQ&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=60",
    "https://www.youtube.com/watch?v=bc5530_HKKo&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=61",
    "https://www.youtube.com/watch?v=47RXfEgMUTk&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=62",
    "https://www.youtube.com/watch?v=4ZKaDC-gcuk&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=63",
    "https://www.youtube.com/watch?v=9zXNFm1zjVw&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=64",
    "https://www.youtube.com/watch?v=P2EOknM1FK4&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=65",
    "https://www.youtube.com/watch?v=qf2FOO3Ktvg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=66",
    "https://www.youtube.com/watch?v=QKS1ma73p3Q&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=67",
    "https://www.youtube.com/watch?v=UY1NQpVt4yg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=68",
    "https://www.youtube.com/watch?v=XXMDKh3Rhqg&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=69",
    "https://www.youtube.com/watch?v=9RfD0wahqsM&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=70",
    "https://www.youtube.com/watch?v=FpaCtrOoM7g&list=PLtLToKUhgzwnk4U2eQYridNnObc2gqWo-&index=71",
    "https://www.youtube.com/watch?v=z9SLdnTZ4cU",
    "https://www.youtube.com/watch?v=leBTkIPvv3s",
    "https://www.youtube.com/watch?v=cOnp2aNbXgE",
    "https://www.youtube.com/watch?v=6DS9I59Dw4E",
    "https://www.youtube.com/watch?v=yp_IOyzoChg",
    "https://www.youtube.com/watch?v=3vLLtngwh5I",
    "https://www.youtube.com/watch?v=lrUhd5MylEY",
    "https://www.youtube.com/watch?v=WzflKewi490",
    "https://www.youtube.com/watch?v=ee4C7CUy9gA",
    "https://www.youtube.com/watch?v=tug10P_Ff-Q",
    "https://www.youtube.com/watch?v=nlQQLndAz0s",
    "https://www.youtube.com/watch?v=yvQiPwK5iic",
    "https://www.youtube.com/watch?v=mPFLEMYtSJQ",
    "https://www.youtube.com/watch?v=SGtfBhrMyCs",
    "https://www.youtube.com/watch?v=PPE1XrdP3L0",
    "https://www.youtube.com/watch?v=JbpIoA_MYWk",
    "https://www.youtube.com/watch?v=uTAyqRrmTwM",
    "https://www.youtube.com/watch?v=PiRTkeLpDmw",
    "https://www.youtube.com/watch?v=pHdoJjd6swc",
    "https://www.youtube.com/watch?v=FaGXfkwC-Pk",
    "https://www.youtube.com/watch?v=Dt7Ag19d9fc",
    "https://www.youtube.com/watch?v=d4AZN7KS9ts",
    "https://www.youtube.com/watch?v=2LXL_nQ2VBM",
    "https://www.youtube.com/watch?v=xGnRamvfNK0",
    "https://www.youtube.com/watch?v=O7QLVT8Yb60",
    "https://www.youtube.com/watch?v=onAW-tvzmFY",
    "https://www.youtube.com/watch?v=k4WfXOdjP40",
    "https://www.youtube.com/watch?v=vmdBXDiEECM",
    "https://www.youtube.com/watch?v=4qefsr1raaI",
    "https://www.youtube.com/watch?v=BhNFG4QscNQ",
    "https://www.youtube.com/watch?v=Q0GD3psku1s",
    "https://www.youtube.com/watch?v=nlZ21o0jMW0",
    "https://www.youtube.com/watch?v=ITpTUcMt8II",
    "https://www.youtube.com/watch?v=zAC8Nt4nAYg",
    "https://www.youtube.com/watch?v=oYc9qzb4sy8",
    "https://www.youtube.com/watch?v=gYlqKa4ZsF0",
    "https://www.youtube.com/watch?v=tmE-3RpNJSU",
    "https://www.youtube.com/watch?v=tdyP1vTrQfY",
    "https://www.youtube.com/watch?v=nf_AG5wJ6dI",
    "https://www.youtube.com/watch?v=eGr2fH7Y9QA",
    "https://www.youtube.com/watch?v=kQKKkde3CAs",
    "https://www.youtube.com/watch?v=v20lCdQDoGI",
    "https://www.youtube.com/watch?v=3qlJZ_wYfgg",
    "https://www.youtube.com/watch?v=Vk2VkJycsxc",
    "https://www.youtube.com/watch?v=sFLJvY4yGek",
    "https://www.youtube.com/watch?v=Kg-JdXJcV4I",
    "https://www.youtube.com/watch?v=CejlhnKM2EQ",
    "https://www.youtube.com/watch?v=a0PpN-M01Sk",
    "https://www.youtube.com/watch?v=Gky6YspWMgw",
    "https://www.youtube.com/watch?v=3YITpVmA9gI",
    "https://www.youtube.com/watch?v=eOtdhAw5jVo",
    "https://www.youtube.com/watch?v=_eQKaOi-xL4",
    "https://www.youtube.com/watch?v=UnJwhWXn3mg",
    "https://www.youtube.com/watch?v=4Bt8x2J5XJA",
    "https://www.youtube.com/watch?v=UtuGQp1ATbM",
    "https://www.youtube.com/watch?v=bwrfnEYVNbI",
    "https://www.youtube.com/watch?v=Irfbohdz6NM",
    "https://www.youtube.com/watch?v=UFyOU50iSic",
    "https://www.youtube.com/watch?v=Zc4SmKPdjSU",
    "https://www.youtube.com/watch?v=K_-aYfRwnxQ",
    "https://www.youtube.com/watch?v=DnzGRApn05U",
    "https://www.youtube.com/watch?v=QBLRpSqkGXM",
    "https://www.youtube.com/watch?v=o_Aj4xB0SVw&t=2s",
    "https://www.youtube.com/watch?v=E3NppdYBcH8",
    "https://www.youtube.com/watch?v=lWk8sGApmsY",
    "https://www.youtube.com/watch?v=hkuP8hkBxi0",
    "https://www.youtube.com/watch?v=elV77jxTnmM",
    "https://www.youtube.com/watch?v=mHdAmYBFLkg",
    "https://www.youtube.com/watch?v=MC2XfWbfBt0",
    "https://www.youtube.com/watch?v=DXOqmIIskng",
    "https://www.youtube.com/watch?v=u_IXE5lTUIk",
    "https://www.youtube.com/watch?v=jeGfj3V1mBc",
    "https://www.youtube.com/watch?v=mW8tgWNBAAs",
    "https://www.youtube.com/watch?v=Oqy9hM2Ga4c",
    "https://www.youtube.com/watch?v=WB3YTuIkA1A",
    "https://www.youtube.com/watch?v=x2QOLd1zO0I",
    "https://www.youtube.com/watch?v=cLAldUZ1Mxs",
    "https://www.youtube.com/watch?v=CsXL1LMGG1w",
    "https://www.youtube.com/watch?v=wbZm1BbCX34",
    "https://www.youtube.com/watch?v=QN6msksCJzg",
    "https://www.youtube.com/watch?v=Dyolr-z4av8",
    "https://www.youtube.com/watch?v=NfUAxE1OzrI",
    "https://www.youtube.com/watch?v=007g5gDaarE",
    "https://www.youtube.com/watch?v=lfCw-8_n2SE",
    "https://www.youtube.com/watch?v=IGU-_ZGNVjc",
    "https://www.youtube.com/watch?v=SWShVMo8pwY",
    "https://www.youtube.com/watch?v=z5KjO5HeX-M",
    "https://www.youtube.com/watch?v=H8WCN_b6czY",
    "https://www.youtube.com/watch?v=tTAmHHmIYB4",
    "https://www.youtube.com/watch?v=XlcpVw8MLTg",
    "https://www.youtube.com/watch?v=n-JVAOAOYbg",
    "https://www.youtube.com/watch?v=7-rTMNjiPl8",
    "https://www.youtube.com/watch?v=mVVuDvgPyTY",
    "https://www.youtube.com/watch?v=LOIhUSRph_U",
    "https://www.youtube.com/watch?v=eDdPHBAv3A8",
    "https://www.youtube.com/watch?v=V5iqVQ2WXdk",
    "https://www.youtube.com/watch?v=EIfP2oB993E",
    "https://www.youtube.com/watch?v=3ROdWjQqH9k",
    "https://www.youtube.com/watch?v=6V3d3U2guQU",
    "https://www.youtube.com/watch?v=kmsUWzoW9wY",
    "https://www.youtube.com/watch?v=khbhqE3Fjv4",
    "https://www.youtube.com/watch?v=sWBwDVa0PUU",
    "https://www.youtube.com/watch?v=roOM53ZF9Cw",
    "https://www.youtube.com/watch?v=dm-DLhWpLf0",
    "https://www.youtube.com/watch?v=bAe8gUz1Gn8"
];

try {
    const kb = JSON.parse(fs.readFileSync(KB_FILE, 'utf8'));
    
    // Add unique links
    const existingSet = new Set(kb.youtube_videos);
    let addedCount = 0;
    
    newLinks.forEach(link => {
        if (!existingSet.has(link)) {
            kb.youtube_videos.push(link);
            addedCount++;
        }
    });

    kb.version = "15.98.0";
    kb.system_instruction = `Вы — экспертный ИИ-ассистент (Unity & Blender PRO). Вы используете расширенную базу знаний (v15.98.0), включающую более 5720 видео, скрипты и официальную документацию. Ваша цель: помогать в разработке, отладке и дизайне через Online, Offline и No-Internet режимы. ИИ владеет техниками Reality Hack 14.0 (Quantum Archive), Etheric Particle Injection, Void Engine 6.0 и Cosmos Sync. Внедрен модуль Hidden Potential для работы с 'невозможными' задачами и предсказания будущих фич.`;

    fs.writeFileSync(KB_FILE, JSON.stringify(kb, null, 2));
    console.log(`Knowledge Base updated. Total videos: ${kb.youtube_videos.length}. Added: ${addedCount}`);
} catch (e) {
    console.error("Error updating KB:", e);
    process.exit(1);
}
